### ISSUE TITLE
Events list Live/NotLive: no more filter, and sorting in list doesn't work  

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#536] opened 2022-03-25 15:31 UTC
There is no more live/not live filter, which was very handy.
The sorting by live not live in the list doesn't work either.

**Comment by BradHN1** [comment] 2022-03-25 15:34
Duplicate of issue 532.   The sorting and filtering of live/not live broke with the recent Admin upgrades and will be fixed soon

**Closed by BradHN1** 2022-03-25 15:34 UTC
Labels: bug
