### ISSUE TITLE
in messages,have messaging user's  email 

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#75] opened 2020-02-05 20:47 UTC
ISSUE 1221
Reported on Fri Dec 20 2019 14:15:57 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium
STATUS =  - Submitted 

Site Url: http://admin.massenergize.org/admin/edit/2/message

Description:
for cadmn, in a message,  can we have the user's  email displayed, along with their name? And if possible, can it by default already be in the "to" box for replying to that user? 

User Role: Community Admin
Notes: cf issue 1248

**Comment by kaatvds** [comment] 2020-02-07 19:52
closed because duplicate of #76

**Closed** 2020-02-07 19:52 UTC
Labels: enhancement
