### ISSUE TITLE
image aspect ratio enforcement

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#39] opened 2020-01-27 20:23 UTC
Pictures gets cut off or squished... let's solve this as onboarding communities and vendors love their eye candy to look good :)
Could be just clear instructions  on size, proportion, resolution for each kind of picture. These are the kinds of pictures:
three home page pics
Event pictures: on Home page, in events list, indiv events page (all different)
Action pictures: on Actions list, indiv action page
Testimonial pictures: in List, in testimonial popup frame (circle)

**Comment by kaatvds** [comment] 2020-03-02 18:48
places where images appear on portal - categories of pics:

1. three pictures on **home** page
----------------
2. **event** cards on homepage
3. event card in all events
4. event cards in individual event
                -------> from 1 source but get cropped in 3 different ways, so hard to design optimally.
-----------------
5. **action** on all actions
6. indiv action
               -------> from 1 source but get cropped in 2 different ways, so hard to design optimally.
-----------------
7. **testimonials** on all testimonials
8. testimonials in indiv testimonials
                -------> from 1 source but get cropped in 2 TOTALLY different ways, hard to design.
-----------------
9.  **service providers** on all service providers
10.  service providers in indiv service provider page
                -------> **this one is in the worst shape. The installer page is super important.**

Simple suggestion: for each category of image, keep the same aspect ratio in each place where they appear (and resize where needed).

We must find another solution for service providers, as some company  have horizontal logos, some vertical, some square some round. Not sure how to do this.

Let's talk abut this on or before next sprint call.

**Comment by jkatofsky** [comment] 2020-05-12 17:34
Here's an outline of the changes I'm thinking of making.

In [FormGenerator](https://github.com/massenergize/frontend-admin/blob/08d6a1376c7b4b4091c688ca78176b12b991985b/v2.0/app/containers/MassEnergizeSuperAdmin/_FormGenerator/index.js#L508), when the `FieldType` is `File`, add new parameters for aspect ratio.

Then, this parameter will be passed to the [MaterialDropZone](https://github.com/massenergize/frontend-admin/blob/08d6a1376c7b4b4091c688ca78176b12b991985b/v2.0/app/components/Forms/MaterialDropZone.js#L42) component which will use it to enforce the aspect ratio of images it receives: not allowing uploads of images that are not within some range of the given aspect ratio, and, _ideally_, bringing up a tool to do necessary cropping within our portal. I will have to figure out the details of these changes to the `MaterialDropZone`.

The idea is for different forms across the portal to easily specify different aspect ratio constraints through a parameter to the form JSON.

Along with this, I would change the [file upload instructions](https://github.com/massenergize/frontend-admin/blob/08d6a1376c7b4b4091c688ca78176b12b991985b/v2.0/app/containers/MassEnergizeSuperAdmin/_FormGenerator/index.js#L519) to be more informative of the new system, perhaps changing it from a Modal to a paragraph so that the instructions are hard-to-miss.

**Comment by BradHN1** [comment] 2020-05-12 23:03
Good idea @jkatofsky; go for it...  @kaatvds @Opoku-Agyemang @ellentohn

**Comment by kaatvds** [comment] 2020-06-06 21:46
This is AWESOME!!!!
One glitch (?). I uploaded the new image, cropped it, pressed submit, it went through and is showing on the portal. However, on the Cadmin it still shows the old pictures as the "current image". The new image is shown as a thumbnail underneath the upload box. Cf screenshot.
![image](https://user-images.githubusercontent.com/30277868/83955121-a55bdb80-a81d-11ea-94cf-80da76247b01.png)

**Comment by kaatvds** [comment] 2020-06-06 22:03
As a cadmin in testimonial same image cropping tool pops up, but it is a little misleading as it seems to show that this is what the image will look like: 
![image](https://user-images.githubusercontent.com/30277868/83955327-ba396e80-a81f-11ea-986b-98cb26eeb5ec.png)
However, on the portal on the all-testimonials page it looks like this (only top part):
![image](https://user-images.githubusercontent.com/30277868/83955340-e228d200-a81f-11ea-9af0-2486480ddd4d.png)
and when "more" is clicked it shows the circular crop:
![image](https://user-images.githubusercontent.com/30277868/83955345-f7056580-a81f-11ea-8432-9d1f4df31849.png)

**Comment by BradHN1** [comment] 2020-06-06 23:15
This has been fixed in the admin portal, but the problem is that the community portal testimonials and other places don't show the entire photo.  Separate issues, we need to sepecify which community portal photos use different specific aspect ratios and enforce them.
Can Kaat and Orly look at this as a design question?  What do we want to show in each place (and ideally it is closer to 4:3 than the testimonial or vendor photos.

**Closed** 2022-08-08 15:44 UTC
Labels: bug, priority 2, priority 3
