### ISSUE TITLE
Testimonials - Ranking link broken and random new tab

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#200] opened 2020-08-26 17:03 UTC
new bug report in CAdmin platform: in testimonials: we may update the order number field within editing any individual testimonial, but it does not update in the display page. Also, upon editing a testimonial a new window opens randomly. Maybe this issue could be integrated with issue #116 for live edit rank? Would make a huge difference.

**Comment by kaatvds** [comment] 2020-11-02 13:30
This is a duplicate of ticket 116. not sure why this is sitting in QA. Should I remove it, or move it  up to validated in CAN>

**Closed** 2020-12-02 20:31 UTC
Labels: bug, priority 2
