### ISSUE TITLE
if user leaves an "other" as under "Who  helped" > can't be seen by Cadmin

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#77] opened 2020-02-05 20:47 UTC
ISSUE 1228
Reported on Mon Dec 30 2019 17:19:19 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = Medium-High
STATUS =  - Submitted 

Site Url: http://admin.massenergize.org/admin/edit/14/testimonial

Description:
if user leaves an "other" as under "Who helped" (which is an AWESOME option!)  it can't be seen by Cadmin in that testimonial's form...

User Role: Community User

**Comment by kaatvds** [comment] 2020-02-19 23:05
closed bec duplicate of #28

**Closed by kaatvds** 2020-02-19 23:05 UTC
Labels: bug, priority 2
